version: '3.8'

services:
  psql:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aviasales_bot_bd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - aviasales-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aviasales_bot_bd"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: khilik/server-bot-aviasales
    depends_on:
      - psql
    environment:
      - DATABASE_URL=postgres://admin:admin@psql:5432/aviasales_bot_bd
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEB_HOOK=${WEB_HOOK}
      - PATH_CERT=/app/cert.pem
      - PATH_KEY=/app/key.pem
    command: go run cmd/app/main.go -tg.token=${TELEGRAM_TOKEN} -tg.webhook=${WEB_HOOK} -tg.cert=${PATH_CERT} -tg.key=${PATH_KEY}
    networks:
      - aviasales-network

volumes:
  db-data:

networks:
  aviasales-network:
    driver: bridge