services:
  psql:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "db-data:/var/lib/postgresql/data"


  # TODO
  # grafana:
  #   build: './config/grafana'
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  #   networks:
  #     monitoring:
  #       aliases:
  #         - grafana

# networks:
#   monitoring:

volumes:
  db-data:
