version: '3.8'

services:
  psql:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aviasales_bot_bd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: khilik/server-bot-aviasales

    environment:
      - DATABASE_URL=postgres://admin:admin@psql:5432/aviasales_bot_bd

volumes:
  db-data:
