name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t khilik/server-bot-aviasales:latest .

    - name: Push Docker image
      run: |
        docker push khilik/server-bot-aviasales:latest

    - name: Update container on server
      run: |
        sshpass -p '${{ secrets.PASSWOR_SERVER }}' ssh -o StrictHostKeyChecking=no ${{ secrets.USER_SERVER }}@${{ secrets.HOST_SERVER }} << EOF
          docker stop aviasales-app-1 || true
          docker rm aviasales-app-1 || true
          docker pull khilik/server-bot-aviasales:latest
          cd projects/aviasales/
          TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" docker compose up --build -d app
        EOF
